#!/bin/env python3
import os, time, pyautogui, datetime
ahora = datetime.datetime.now()

pyautogui.FAILSAFE = False
pyautogui.click(90, 755)
#pyautogui.click(90, 561)
time.sleep(2)
pyautogui.typewrite('http://192.168.1.1/')
time.sleep(0.1)
pyautogui.press('right')
time.sleep(0.1)
pyautogui.press('enter')
time.sleep(2)
pyautogui.press('down')
time.sleep(.5)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.press('tab', presses=2)
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(2.5)
pyautogui.press('tab', presses=2)
time.sleep(0.2)
pyautogui.press('tab', presses=2)
time.sleep(0.2)
pyautogui.press('tab', presses=2)
time.sleep(0.2)
pyautogui.press('tab')
pyautogui.typewrite('http://192.168.1.1/getpage.gch?pid=1002&nextpage=manager_dev_conf_t.gch')
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('tab')
time.sleep(0.1)
pyautogui.press('tab')
time.sleep(0.1)
pyautogui.press('enter')
time.sleep(0.1)
pyautogui.press('left')
time.sleep(0.1)
pyautogui.press('enter') #print('     -- Se reinicia router') 
print (f'{ahora.strftime("%d/%m/%Y")},{ahora.strftime("%H:%M")},Reiniciado,Reiniciado')
time.sleep(10) 
os.system('reboot')
   